# Site Build Settings

# Site metadata (critical for SEO)
url:                 'https://takeshimg92.github.io'
baseurl:             ''
title:               'KakkoKari'
description:         'Another (data) science blog. By Alessandro Morita'
author:
  name:              'Alessandro Morita'
  email:             'takeshi.gagliardi@gmail.com'
lang:                'en'

# Default image for social sharing (Open Graph / Twitter cards)
logo:                '/assets/img/sake.jpg'

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:categories/:title/
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Alessandro Morita"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
